//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureTrainingDBLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailMessage
    {
        public int Id { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public string FromEmailId { get; set; }
        public string ToEmailIds { get; set; }
        public string CCEmailIds { get; set; }
        public bool HasAttachment { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime SentDate { get; set; }
    }
}
